# Generated by Django 4.2.16 on 2024-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookableservice_availability_bookableservice_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookableservice',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='bookableservice',
            name='location',
            field=models.CharField(default='Location', max_length=200),
        ),
    ]
